<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Loupedeck.EverQuestPlugin</RootNamespace>
    <LangVersion>latest</LangVersion>

    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <DebugType>none</DebugType>

    <PluginApiDir>C:\Program Files\Logi\LogiPluginService\</PluginApiDir>
    <PluginDir>$(LocalAppData)\Logi\LogiPluginService\Plugins\</PluginDir>

    <BaseOutputPath>$(MSBuildProjectDirectory)\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\obj\</BaseIntermediateOutputPath>
    <OutputPath>$(BaseOutputPath)$(Configuration)\bin\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PluginApi">
      <HintPath>$(PluginApiDir)PluginApi.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyPackage" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <PackageFiles Include="package\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(PackageFiles)" DestinationFolder="$(OutputPath)..\%(RecursiveDir)" />
  </Target>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="echo $(BaseOutputPath)$(Configuration)\ &gt; &quot;$(PluginDir)$(ProjectName).link&quot;&#xD;&#xA;start loupedeck:plugin/EverQuest/reload" />
  </Target>

  <Target Name="PluginClean" AfterTargets="CoreClean">
    <Delete Files="$(PluginDir)$(ProjectName).link" />
    <RemoveDir Directories="$(OutputPath)..\" />
  </Target>

</Project>
